steam.path = "${XDG_DATA_HOME}/Steam"
proton.path = "${XDG_DATA_HOME}/Steam/steamapps/common/Proton 8.0"
livesplit.path = "${XDG_DATA_HOME}/LiveSplit"

# Common environment variables.
[envs.common]
WINEDLLOVERRIDES="dinput8=n,b"

# Dark Souls III specific environment variables.
[envs."DarkSoulsIII"]
DOLL_SKIP="consistent"

[envs."DarkSoulsIII".deps]
after = ["common"]

# Dark Souls III specific settings.
[games."DarkSoulsIII"]
app_id = "374320"
env = "DarkSoulsIII"

# These paths should be changed manually.
[games."DarkSoulsIII".paths]
"1.04" = "/mnt/Patches/DARK SOULS III/1.04/Game/DarkSoulsIII.exe"
"1.08" = "/mnt/Patches/DARK SOULS III/1.08/Game/DarkSoulsIII.exe"
"1.12" = "/mnt/Patches/DARK SOULS III/1.12/Game/DarkSoulsIII.exe"
"1.15.1" = "/mnt/Patches/DARK SOULS III/1.15.1/Game/DarkSoulsIII.exe"
